# Generated by Django 4.2.5 on 2023-10-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinario',
            old_name='apellidoVet',
            new_name='apellido_Vet',
        ),
        migrations.RenameField(
            model_name='veterinario',
            old_name='veterinario',
            new_name='nombre_vet',
        ),
    ]
