# Generated by Django 4.2 on 2023-10-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVeterinaria', '0002_rename_apellidovet_veterinario_apellido_vet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinario',
            old_name='apellido_Vet',
            new_name='apellido_vet',
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
